# APS Failure at Scania Trucks

Dataset is from https://archive.ics.uci.edu/dataset/421/aps+failure+at+scania+trucks

n = 60000

171 features

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/maxxxxc/SIR-Summer-2023/main/dataset/aps_failure_test_set.csv"
#df = pd.read_csv(url, na_values = 'na')

In [3]:
# Read the training dataset from CSV
train_df = pd.read_csv(url, na_values = 'na')

# Read the test dataset from CSV
test_df = pd.read_csv(url, na_values = 'na')

# Add a 'Label' column to the test dataset and fill it with NaN values
#test_df['Label'] = float('nan')

# Concatenate the training and test datasets
df = pd.concat([train_df, test_df], ignore_index=True)

# Save the combined dataset to a new CSV file
df.to_csv('combined.csv', index=False)

In [4]:
df.shape

(32000, 171)

In [5]:
print(df.head())

  class  aa_000  ab_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  \
0   neg      60     0.0    20.0    12.0     0.0     0.0     0.0     0.0   
1   neg      82     0.0    68.0    40.0     0.0     0.0     0.0     0.0   
2   neg   66002     2.0   212.0   112.0     0.0     0.0     0.0     0.0   
3   neg   59816     NaN  1010.0   936.0     0.0     0.0     0.0     0.0   
4   neg    1814     NaN   156.0   140.0     0.0     0.0     0.0     0.0   

   ag_002  ...    ee_002    ee_003    ee_004    ee_005     ee_006    ee_007  \
0     0.0  ...    1098.0     138.0     412.0     654.0       78.0      88.0   
1     0.0  ...    1068.0     276.0    1620.0     116.0       86.0     462.0   
2     0.0  ...  495076.0  380368.0  440134.0  269556.0  1315022.0  153680.0   
3     0.0  ...  540820.0  243270.0  483302.0  485332.0   431376.0  210074.0   
4     0.0  ...    7646.0    4144.0   18466.0   49782.0     3176.0     482.0   

     ee_008  ee_009  ef_000  eg_000  
0       0.0     0.0     0.0     0.0 

In [6]:
missing_values_count = df.isna().sum()

print(missing_values_count.sort_values(ascending = False))

br_000    26258
bq_000    25962
bp_000    25442
bo_000    24752
ab_000    24726
          ...  
cj_000      172
ci_000      172
bt_000       56
aa_000        0
class         0
Length: 171, dtype: int64


In [7]:
from sklearn import svm
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [8]:
X = df.drop("class", axis=1)
y = df["class"]

In [9]:
#preprocessing for na values
threshold = len(X) * 0.5
X = X.dropna(thresh = threshold, axis = 1)

X = X.fillna(X.mean())

In [10]:
X.head()

aa_000  ac_000  ad_000  ae_000  af_000  ag_000  ag_001  ag_002    ag_003  \
0      60    20.0    12.0     0.0     0.0     0.0     0.0     0.0    2682.0   
1      82    68.0    40.0     0.0     0.0     0.0     0.0     0.0       0.0   
2   66002   212.0   112.0     0.0     0.0     0.0     0.0     0.0  199486.0   
3   59816  1010.0   936.0     0.0     0.0     0.0     0.0     0.0       0.0   
4    1814   156.0   140.0     0.0     0.0     0.0     0.0     0.0       0.0   

      ag_004  ...    ee_002    ee_003    ee_004    ee_005     ee_006  \
0     4736.0  ...    1098.0     138.0     412.0     654.0       78.0   
1      748.0  ...    1068.0     276.0    1620.0     116.0       86.0   
2  1358536.0  ...  495076.0  380368.0  440134.0  269556.0  1315022.0   
3   123922.0  ...  540820.0  243270.0  483302.0  485332.0   431376.0   
4       72.0  ...    7646.0    4144.0   18466.0   49782.0     3176.0   

     ee_007    ee_008  ee_009  ef_000  eg_000  
0      88.0       0.0     0.0     0.0     0.0  
1     462.0       0.0     0.0     0.0     0.0  
2  153680.0     516.0     0.0     0.0     0.0  
3  210074.0  281662.0  3232.0     0.0     0.0  
4     482.0      76.0     0.0     0.0     0.0  

[5 rows x 162 columns]

In [11]:
y.value_counts()

neg    31250
pos      750
Name: class, dtype: int64

In [12]:
X.shape

(32000, 162)

In [13]:
y = y.replace({"neg" : 0, "pos" : 1})
y.value_counts()

0    31250
1      750
Name: class, dtype: int64

## Logistic Regression

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Create and train the logistic regression model
#model = LogisticRegression()
model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)

# Make predictions on the test set
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)

# Calculate accuracy
accuracy = accuracy_score(y_train, y_train_pred)
print("Test Accuracy:", accuracy)
accuracy = accuracy_score(y_test, y_test_pred)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9905729166666667
Test Accuracy: 0.987734375


C:\Users\panda\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Divide and Conquer

Divide the training data into 11 batches, train a logistic model on each of the batch, and then combine the 11 prediction results. Consider the following two ensemble methods:
- majority voting
- average (or sum) of the logit output and then make decision based on its sign

In [15]:
def iterate_process(X, y):
    # Split the data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)
    
    # Define the number of batches
    num_batches = 11
    
    # Randomly shuffle the data indices
    #indices = np.random.permutation(len(X))
    
    #change 7/12
    indices = np.random.permutation(len(X_train))
    
    # Calculate the batch size
    batch_size = len(X_train) // num_batches
    
    # Make predictions on the test set using majority voting
    preds_voting = np.zeros(len(y_test))
    # Make predictions on the test set using average of logit
    preds_logit = np.zeros(len(y_test))
    #Make predictions on the test set using average of probs
    preds_prob = np.zeros(len(y_test))

    
    # Split the training data into batches, fit a logistic regression model on each batch
    for i in range(num_batches):
        # Calculate the starting and ending indices for the current batch
        start_index = i * batch_size
        end_index = (i + 1) * batch_size
        
        # Create a logistic regression model
        model = LogisticRegression(max_iter=500)
        
        # Select the current batch for training
        X_batch = X_train.iloc[indices[start_index:end_index]]
        y_batch = y_train.iloc[indices[start_index:end_index]]
        
        scaler = StandardScaler()
        X_batch_scaled = scaler.fit_transform(X_batch)
        X_test_scaled = scaler.transform(X_test)
        
        # Fit the model on the current batch
        model.fit(X_batch_scaled, y_batch)
               
        y_pred = model.predict(X_test_scaled)
        # Accumulate the predictions using majority voting
        preds_voting += (y_pred == 1)
    
        # Accumulate the predictions using majority voting
        y_pred = model.decision_function(X_test_scaled)
        preds_logit += y_pred
        
        #Accumulate the probs
        y_pred = model.predict_proba(X_test_scaled)
        preds_prob += y_pred[:,1]
   
    
    accuracy = np.zeros(4)
    
    # Majority voting (selecting the most frequent prediction for each sample)
    final_predictions = np.where(preds_voting > num_batches / 2, 1, 0)
    accuracy[0] = accuracy_score(y_test, final_predictions)
    # Average of logit
    final_predictions = np.where(preds_logit > 0, 1, 0)
    accuracy[1] = accuracy_score(y_test, final_predictions)
    #Average of probs
    final_predictions = np.where(preds_prob / num_batches > 0.5, 1, 0)
    accuracy[2] = accuracy_score(y_test, final_predictions)
    
    # Train a model on all 11 batches of training data
    model = LogisticRegression(max_iter=500)
    
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy[3] = accuracy_score(y_test, y_pred)
    
    return accuracy

Try the divide and conquer approaches 10 times, reporting the following error matrix. 
- 10-by-4
- col_1: majority voting
- col_2: average the logit
- col_3: average probabilities
- col_4: using the model trained on all the training data

In [16]:
# Number of times to repeat the process
num_repeats = 50

# Initialize an empty matrix (10-by-4) to store accuracies
accuracies = np.zeros((num_repeats, 4))

seed = 42
# Repeat the process and store accuracies
for i in range(num_repeats):
    np.random.seed(seed)
    accuracies[i] = iterate_process(X, y)
    seed += 2

# Print the accuracies
print("Accuracies:", accuracies)

Accuracies: [[0.9884375  0.98554688 0.988125   0.990625  ]
 [0.98882812 0.98710937 0.98914062 0.99070313]
 [0.98898438 0.98726563 0.98882812 0.99046875]
 [0.989375   0.98820312 0.98945313 0.9909375 ]
 [0.98773438 0.98515625 0.98835938 0.98960938]
 [0.986875   0.9859375  0.98734375 0.98882812]
 [0.98929687 0.98664063 0.98914062 0.99195312]
 [0.98796875 0.98671875 0.98820312 0.99171875]
 [0.9875     0.98546875 0.98757812 0.99054688]
 [0.98898438 0.98765625 0.98921875 0.99140625]
 [0.98929687 0.9865625  0.98859375 0.99007813]
 [0.98914062 0.98796875 0.98875    0.99179688]
 [0.98875    0.98890625 0.9890625  0.99078125]
 [0.989375   0.98734375 0.9896875  0.99070313]
 [0.9878125  0.98710937 0.9878125  0.98984375]
 [0.98960938 0.98796875 0.98945313 0.99195312]
 [0.988125   0.9871875  0.98789063 0.98984375]
 [0.98890625 0.98859375 0.98851563 0.99140625]
 [0.98851563 0.98734375 0.98828125 0.98992187]
 [0.98710937 0.98460938 0.98734375 0.98945313]
 [0.98828125 0.9846875  0.98820312 0.99101562]
 

In [17]:
np.mean(accuracies, axis = 0)

array([0.98844531, 0.98688125, 0.98847812, 0.99044687])

In [18]:
np.std(accuracies, axis = 0)

array([0.00086873, 0.00113212, 0.00089326, 0.00084621])